-- 코드를 입력하세요
# SELECT * from book;
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' 
AND PUBLISHED_DATE >= '2021-01-01' and PUBLISHED_DATE < '2022-01-01'
ORDER BY PUBLISHED_DATE ASC;